services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=meubanco
      - DB_USER=meuusuario
      - DB_PASSWORD=senhasecreta

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: senhasecreta
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: