# Generated by Django 2.2.5 on 2019-11-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesagem',
            old_name='Residuo',
            new_name='residuo',
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
